### ISSUE TITLE
Timeline year view does not allow slotDuration of 1 day without also having labels on each day

### ISSUE THREAD

**Issue by vjmartins** [fullcalendar/fullcalendar#4937]
Hi..

First, awesome job. Big fan!

Im trying to create a 365 days timeline and i like to remove/hide day label. Its possible?

![timeline365](https://user-images.githubusercontent.com/827692/58474276-950d1d00-8142-11e9-9328-5aa3b1467d91.png)

Any help?

PS: Sorry my english

**Comment by arshaw** [comment]
you might notice the warning `slotLabelInterval must be a multiple of slotDuration`. preventing people from doing this was intentional, but I don't see why we shouldn't allow it. we prevented it because otherwise internally things were more difficult to implement (the top label could span arbitrary numbers of days, 28-31. much easier to keep that constant)

**Comment by irega** [comment]
Hi!! 

In our production project, we need the same functionality requested by @vjmartins in this issue. We need to display a calendar with the 365 days of the year (with slots of 1 day) and the headers should contain the month name.

The issue is the year view is shown with all months but the events are fitting to the full month in this way:

![image](https://user-images.githubusercontent.com/11742038/79346336-83875c00-7f32-11ea-84ad-df7664ec1a9b.png)

We have implemented these two examples to reproduce the issue. One example is with JS Vanilla and the other one is with Angular.

https://codepen.io/irega/pen/bGVEwVv
https://codesandbox.io/s/headless-leaf-uxx2b

In this other example, we have used jquery and an older version of fullcalendar, which seems to work fine:

https://jsfiddle.net/9np7k0au/

Any suggestion? Thanks you!

**Comment by acerix** [comment]
For reference, a possible hack is to remove the labels from datesRenders:

https://codepen.io/acerix/pen/YzywYeV?editors=0010

**Comment by ghry5** [comment]
Any way to do this in v5? I cannot seem to completeley remove a row with the Slot Label Hooks.

**Comment by asadakbar** [comment]
There is no way to do this in v5 because the header row which contains the slot header such as date does not render until after the view renders. Using the viewDidMount hook shows every other header row rendered except the one that is directly atop the slot. 

And when using the slotDidMount hook, the box for the date header still shows itself, or the entire slot is removed from the view.

**Comment by asadakbar** [comment]
@acerix I used the viewDidMount hook to duplicate what you suggested for version 5, however after it was removed from the hook, the header row got added back. I couldn't figure out why that was occurring.

**Comment by asadakbar** [comment]
After trying to use slotLabelDidMount to atleast remove the a tag with the label text, I've found that the same thing happens as viewDidMount. After the removal in the hook, the label is added back.

**Comment by acerix** [comment]
The same hack doens't work in v5, but hiding the labels with CSS seems to work ok:

https://codepen.io/acerix/pen/NWRxbba?editors=0110

**Comment by acerix** [comment]
For reference, the same for minute precision:

https://codepen.io/acerix/pen/Rwxppaj?editors=0110

**Comment by adri95cadiz** [comment]
Bump. 

Is this going to be done? It has been confirmed for 5 years...

**Comment by Bliqui** [comment]
+1

**Comment by Bliqui** [comment]
> The same hack doens't work in v5, but hiding the labels with CSS seems to work ok:
> 
> https://codepen.io/acerix/pen/NWRxbba?editors=0110

@acerix, Thank you for a nice solution. Do you know how to remove the slot's vertical borders in some smart way? I'm trying to achieve a view like this:

![Screenshot 2024-10-04 at 15 18 07](https://github.com/user-attachments/assets/de0116e5-216b-4926-b428-b8ba818ccaa0)
