### ISSUE TITLE
scrollTime does not always work on prev/next

### ISSUE THREAD

**Issue by SelectSystemsInternational** [fullcalendar/fullcalendar#5351]
This problem seems to only happen in Chrome and Opera Browser not in Firefox
Select Week Mode - scrollTime is not set to 6am but reset back 12am. 
When you use the arrows to step between the weeks back and forward every second week scrollTime is not set to 6am but reset back 12am. 
Here is a link to an example code to show the problem
https://selectsystems.com.au/html/timeline-column-grouping.html

**Comment by acerix** [comment]
Thanks, confirmed.  Your demo doesn't run for me because of jquery over http but I get the same result in codepen:

https://codepen.io/acerix/pen/abvOgvM?editors=0010

**Comment by SelectSystemsInternational** [comment]
Also if you add weekNumbers: true, 
It also has the same problem on resourceTimelineDay view
See https://codepen.io/SelectSystemsInternational/pen/xxwwVLj

**Comment by SelectSystemsInternational** [comment]
This has been fixed in the v5 RC but if you use nowIndicator: true this causes the scroll time to be not correct when clicking Today. Dont know if this is the default behaviour ?
See https://codepen.io/SelectSystemsInternational/pen/xxwwVLj

**Comment by arshaw** [comment]
still in the latest v5: https://codepen.io/arshaw/pen/yLezRxp?editors=0010

it consistently happens to me when ui press next for the first time

**Comment by arshaw** [comment]
the scroll seems to be incorrect during spans of time that display the nowIndicator

**Comment by arshaw** [comment]
I thought I would have been fixed in v5.2.0, but there is subtly different buggy behavior:

- v5.1.0 - [demo](https://codepen.io/arshaw/pen/KKVOREa?editors=0010) - ignores scrollTime when moving AWAY from the current day
- v5.2.0 - [demo](https://codepen.io/arshaw/pen/yLezRxp) - ignores scrollTime when moving back TO the current day

I'll keep this ticket open and attempt to fix again in the next release.

**Comment by arshaw** [comment]
^my comments above express how the bug is still sometimes present when navigating prev/next, but for navigating between views, the bug seems completely fixed

**Comment by arshaw** [comment]
i fixed this again here:
https://github.com/fullcalendar/fullcalendar-scheduler/commit/c9fc5b3a6b832f1e8ba1182e5ca688b5b3faf16a

i'll release very soon

**Comment by arshaw** [comment]
this has been fixed in [5.3.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v5.3.0)

update demo: https://codepen.io/arshaw/pen/yLezRxp

**Comment by LeoLaana** [comment]
Hi, I am using fullcalendar v5.3.2 and have set scrollTime: '14:00'
but the vertical scroll always starts on the top which is 12 am .
same behavior in daily and weekly view.
